#!/bin/ksh
#
# $OpenBSD$

daemon="/usr/local/bin/python3"
daemon_flags="/usr/local/lib/nonstatic/nonstatic.py"
daemon_user="_nonstatic"

. /etc/rc.d/rc.subr

pexp="/usr/local/bin/python3 /usr/local/lib/nonstatic/nonstatic.py"
rc_bg=YES

rc_pre() {
	install -d -o _nonstatic -g wheel -m 0755 /var/run/nonstatic
}

rc_cmd "$1"
